public class Arithmatic {
    public void sum(Decimal a, Decimal b){
    }
    public void sum(Decimal a, Integer b){
    }
    public Integer sum(Integer a, Integer b){
        return a + 1;
    }
    public void sum(Integer a, Integer b, Integer c){
    }
    public void sum(Integer a, Integer b, Integer c, Integer d){
    }
    public Integer sum(Integer a, Integer b, Integer c, Integer d, Integer e){
        return a+b+c+d+e;
    }
    // Arithmatic ar = new Arithmatic();
    // Integer sum = ar.sum(1,2,34,5,5);
}