public class CurrencyConvertorWrapper {
    public boolean success;
    public Integer timestamp;
    public String source;
    public quotes quotes;
    public class quotes {
        public Double GBPAED;
        public Double GBPAFN;
        public Double GBPALL;
        public Double GBPAMD;
        public Double GBPANG;
        public Double GBPAOA;
        public Double GBPARS;
        public Double GBPAUD;
        public Double GBPAWG;
        public Double GBPAZN;
        public Double GBPBAM;
        public Double GBPBBD;
        public Double GBPBDT;
        public Double GBPBGN;
        public Double GBPBHD;
        public Double GBPBIF;
        public Double GBPBMD;
        public Double GBPBND;
        public Double GBPBOB;
        public Double GBPBRL;
    }
}